import { useState, useRef, useEffect } from 'react';
import api, { SERVER_URL } from '../lib/api';

export default function ThumbnailGenerator({ thumbnailUrl, onThumbnailChange, lessonFiles }) {
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');
  const fileInputRef = useRef(null);
  const autoGeneratedRef = useRef(false);

  // البحث عن أول ملف PDF في ملفات الدرس
  const firstPdf = lessonFiles?.find(f => f.type === 'application/pdf' || f.name?.endsWith('.pdf'));

  // توليد تلقائي عند إضافة أول PDF
  useEffect(() => {
    if (firstPdf && !thumbnailUrl && !loading && !autoGeneratedRef.current) {
      autoGeneratedRef.current = true;
      handleGenerateFromPdf(firstPdf);
    }
    if (!firstPdf) {
      autoGeneratedRef.current = false;
    }
  }, [firstPdf]); // eslint-disable-line react-hooks/exhaustive-deps

  const handleGenerateFromPdf = async (file) => {
    if (!file) return;
    setLoading(true);
    setError('');
    try {
      const fd = new FormData();
      fd.append('file', file);
      const res = await api.post('/tools/thumbnail/generate', fd, {
        headers: { 'Content-Type': 'multipart/form-data' },
      });
      onThumbnailChange(res.data.thumbnailUrl);
    } catch (err) {
      setError(err.response?.data?.message || 'خطأ في توليد الصورة المصغرة');
    } finally {
      setLoading(false);
    }
  };

  const handleUploadCustom = async (file) => {
    if (!file) return;
    setLoading(true);
    setError('');
    try {
      const fd = new FormData();
      fd.append('file', file);
      const res = await api.post('/tools/thumbnail/upload', fd, {
        headers: { 'Content-Type': 'multipart/form-data' },
      });
      onThumbnailChange(res.data.thumbnailUrl);
    } catch (err) {
      setError(err.response?.data?.message || 'خطأ في رفع الصورة');
    } finally {
      setLoading(false);
    }
  };

  const handleCustomImageSelect = (e) => {
    const file = e.target.files?.[0];
    if (!file) return;
    if (!file.type.startsWith('image/')) {
      setError('يجب اختيار صورة');
      return;
    }
    handleUploadCustom(file);
  };

  const handleRemove = () => {
    onThumbnailChange('');
    autoGeneratedRef.current = false;
    setError('');
  };

  const handleRegenerate = () => {
    if (firstPdf) {
      handleGenerateFromPdf(firstPdf);
    }
  };

  return (
    <div className="flex items-start gap-3">
      {error && (
        <p className="text-red-500 text-xs">{error}</p>
      )}

      {/* حالة التحميل */}
      {loading && (
        <div className="flex items-center gap-2">
          <div className="w-14 h-[72px] rounded-lg bg-gray-100 border border-gray-200 flex items-center justify-center shrink-0">
            <div className="w-5 h-5 border-2 border-blue-200 border-t-blue-600 rounded-full animate-spin"></div>
          </div>
          <span className="text-xs text-gray-400">جاري التوليد...</span>
        </div>
      )}

      {/* المعاينة - عند وجود صورة */}
      {!loading && thumbnailUrl && (
        <div className="flex items-center gap-3">
          <div className="relative group shrink-0">
            <img
              src={`${SERVER_URL}${thumbnailUrl}`}
              alt="صورة مصغرة"
              className="w-14 h-[72px] object-cover rounded-lg border border-gray-200 shadow-sm"
            />
            <div className="absolute inset-0 bg-black/40 rounded-lg opacity-0 group-hover:opacity-100 transition-opacity flex items-center justify-center gap-1">
              {firstPdf && (
                <button
                  type="button"
                  onClick={handleRegenerate}
                  className="w-6 h-6 bg-white rounded-full text-blue-600 text-xs flex items-center justify-center hover:bg-blue-50"
                  title="إعادة توليد"
                >
                  ↻
                </button>
              )}
              <button
                type="button"
                onClick={() => fileInputRef.current?.click()}
                className="w-6 h-6 bg-white rounded-full text-amber-600 text-xs flex items-center justify-center hover:bg-amber-50"
                title="صورة مخصصة"
              >
                ✎
              </button>
              <button
                type="button"
                onClick={handleRemove}
                className="w-6 h-6 bg-white rounded-full text-red-600 text-xs flex items-center justify-center hover:bg-red-50"
                title="إزالة"
              >
                ✕
              </button>
            </div>
          </div>
          <div>
            <p className="text-xs text-emerald-600 font-medium">تم التوليد</p>
            <p className="text-[10px] text-gray-400">400×566</p>
          </div>
        </div>
      )}

      {/* حالة عدم وجود صورة وعدم تحميل */}
      {!loading && !thumbnailUrl && (
        <div className="flex items-center gap-2">
          {firstPdf ? (
            <button
              type="button"
              onClick={handleRegenerate}
              className="flex items-center gap-1.5 px-3 py-1.5 bg-blue-50 text-blue-600 rounded-lg text-xs hover:bg-blue-100 transition-colors border border-blue-200"
            >
              توليد من PDF
            </button>
          ) : (
            <button
              type="button"
              onClick={() => fileInputRef.current?.click()}
              className="flex items-center gap-1.5 px-3 py-1.5 bg-gray-50 text-gray-500 rounded-lg text-xs hover:bg-gray-100 transition-colors border border-gray-200"
            >
              رفع صورة
            </button>
          )}
          <span className="text-[10px] text-gray-400">
            {firstPdf ? 'أو' : 'ارفع PDF ليتم التوليد تلقائياً'}
          </span>
          {firstPdf && (
            <button
              type="button"
              onClick={() => fileInputRef.current?.click()}
              className="text-xs text-gray-400 hover:text-gray-600 underline"
            >
              صورة مخصصة
            </button>
          )}
        </div>
      )}

      <input
        ref={fileInputRef}
        type="file"
        accept=".jpg,.jpeg,.png,.webp"
        onChange={handleCustomImageSelect}
        className="hidden"
      />
    </div>
  );
}
